name: Go
on: [push, pull_request]
jobs:
  build:
    name: Test 
    strategy:
      matrix:
        go: [1.13, 1.14, 1.15]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch
    steps:
    - run: go get golang.org/x/tools/cmd/goimports
    - run: go get golang.org/x/lint/golint
    - uses: actions/checkout@v2
    - run: ./gotest.sh
